//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Appa.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SoapServiceSoap")]
    public interface SoapServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.IAsyncResult BeginHelloWorld(Appa.ServiceReference1.HelloWorldRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.HelloWorldResponse EndHelloWorld(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Login", ReplyAction="*")]
        System.IAsyncResult BeginLogin(Appa.ServiceReference1.LoginRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.LoginResponse EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddAdmin", ReplyAction="*")]
        System.IAsyncResult BeginAddAdmin(Appa.ServiceReference1.AddAdminRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.AddAdminResponse EndAddAdmin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddClient", ReplyAction="*")]
        System.IAsyncResult BeginAddClient(Appa.ServiceReference1.AddClientRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.AddClientResponse EndAddClient(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Validate", ReplyAction="*")]
        System.IAsyncResult BeginValidate(Appa.ServiceReference1.ValidateRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.ValidateResponse EndValidate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UsedCoupons", ReplyAction="*")]
        System.IAsyncResult BeginUsedCoupons(Appa.ServiceReference1.UsedCouponsRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.UsedCouponsResponse EndUsedCoupons(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UnUsedCoupons", ReplyAction="*")]
        System.IAsyncResult BeginUnUsedCoupons(Appa.ServiceReference1.UnUsedCouponsRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.UnUsedCouponsResponse EndUnUsedCoupons(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AllCoupons", ReplyAction="*")]
        System.IAsyncResult BeginAllCoupons(Appa.ServiceReference1.AllCouponsRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.AllCouponsResponse EndAllCoupons(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Test", ReplyAction="*")]
        System.IAsyncResult BeginTest(Appa.ServiceReference1.TestRequest request, System.AsyncCallback callback, object asyncState);
        
        Appa.ServiceReference1.TestResponse EndTest(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Appa.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Appa.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Appa.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shop;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string shop) {
            this.shop = shop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Appa.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAdmin", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.AddAdminRequestBody Body;
        
        public AddAdminRequest() {
        }
        
        public AddAdminRequest(Appa.ServiceReference1.AddAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shop;
        
        public AddAdminRequestBody() {
        }
        
        public AddAdminRequestBody(string shop) {
            this.shop = shop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.AddAdminResponseBody Body;
        
        public AddAdminResponse() {
        }
        
        public AddAdminResponse(Appa.ServiceReference1.AddAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddAdminResult;
        
        public AddAdminResponseBody() {
        }
        
        public AddAdminResponseBody(string AddAdminResult) {
            this.AddAdminResult = AddAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClient", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.AddClientRequestBody Body;
        
        public AddClientRequest() {
        }
        
        public AddClientRequest(Appa.ServiceReference1.AddClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shop;
        
        public AddClientRequestBody() {
        }
        
        public AddClientRequestBody(string shop) {
            this.shop = shop;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.AddClientResponseBody Body;
        
        public AddClientResponse() {
        }
        
        public AddClientResponse(Appa.ServiceReference1.AddClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddClientResult;
        
        public AddClientResponseBody() {
        }
        
        public AddClientResponseBody(string AddClientResult) {
            this.AddClientResult = AddClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(Appa.ServiceReference1.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adminId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string coupon;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string adminId, string coupon) {
            this.adminId = adminId;
            this.coupon = coupon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(Appa.ServiceReference1.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(string ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsedCouponsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsedCoupons", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.UsedCouponsRequestBody Body;
        
        public UsedCouponsRequest() {
        }
        
        public UsedCouponsRequest(Appa.ServiceReference1.UsedCouponsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsedCouponsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdminId;
        
        public UsedCouponsRequestBody() {
        }
        
        public UsedCouponsRequestBody(string AdminId) {
            this.AdminId = AdminId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsedCouponsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsedCouponsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.UsedCouponsResponseBody Body;
        
        public UsedCouponsResponse() {
        }
        
        public UsedCouponsResponse(Appa.ServiceReference1.UsedCouponsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsedCouponsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsedCouponsResult;
        
        public UsedCouponsResponseBody() {
        }
        
        public UsedCouponsResponseBody(string UsedCouponsResult) {
            this.UsedCouponsResult = UsedCouponsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnUsedCouponsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnUsedCoupons", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.UnUsedCouponsRequestBody Body;
        
        public UnUsedCouponsRequest() {
        }
        
        public UnUsedCouponsRequest(Appa.ServiceReference1.UnUsedCouponsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnUsedCouponsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdminId;
        
        public UnUsedCouponsRequestBody() {
        }
        
        public UnUsedCouponsRequestBody(string AdminId) {
            this.AdminId = AdminId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnUsedCouponsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnUsedCouponsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.UnUsedCouponsResponseBody Body;
        
        public UnUsedCouponsResponse() {
        }
        
        public UnUsedCouponsResponse(Appa.ServiceReference1.UnUsedCouponsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnUsedCouponsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UnUsedCouponsResult;
        
        public UnUsedCouponsResponseBody() {
        }
        
        public UnUsedCouponsResponseBody(string UnUsedCouponsResult) {
            this.UnUsedCouponsResult = UnUsedCouponsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllCouponsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllCoupons", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.AllCouponsRequestBody Body;
        
        public AllCouponsRequest() {
        }
        
        public AllCouponsRequest(Appa.ServiceReference1.AllCouponsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllCouponsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Password;
        
        public AllCouponsRequestBody() {
        }
        
        public AllCouponsRequestBody(string Password) {
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllCouponsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllCouponsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.AllCouponsResponseBody Body;
        
        public AllCouponsResponse() {
        }
        
        public AllCouponsResponse(Appa.ServiceReference1.AllCouponsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllCouponsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AllCouponsResult;
        
        public AllCouponsResponseBody() {
        }
        
        public AllCouponsResponseBody(string AllCouponsResult) {
            this.AllCouponsResult = AllCouponsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(Appa.ServiceReference1.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Appa.ServiceReference1.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(Appa.ServiceReference1.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapServiceSoapChannel : Appa.ServiceReference1.SoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsedCouponsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UsedCouponsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnUsedCouponsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UnUsedCouponsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AllCouponsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AllCouponsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceSoapClient : System.ServiceModel.ClientBase<Appa.ServiceReference1.SoapServiceSoap>, Appa.ServiceReference1.SoapServiceSoap {
        
        private BeginOperationDelegate onBeginHelloWorldDelegate;
        
        private EndOperationDelegate onEndHelloWorldDelegate;
        
        private System.Threading.SendOrPostCallback onHelloWorldCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddAdminDelegate;
        
        private EndOperationDelegate onEndAddAdminDelegate;
        
        private System.Threading.SendOrPostCallback onAddAdminCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddClientDelegate;
        
        private EndOperationDelegate onEndAddClientDelegate;
        
        private System.Threading.SendOrPostCallback onAddClientCompletedDelegate;
        
        private BeginOperationDelegate onBeginValidateDelegate;
        
        private EndOperationDelegate onEndValidateDelegate;
        
        private System.Threading.SendOrPostCallback onValidateCompletedDelegate;
        
        private BeginOperationDelegate onBeginUsedCouponsDelegate;
        
        private EndOperationDelegate onEndUsedCouponsDelegate;
        
        private System.Threading.SendOrPostCallback onUsedCouponsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUnUsedCouponsDelegate;
        
        private EndOperationDelegate onEndUnUsedCouponsDelegate;
        
        private System.Threading.SendOrPostCallback onUnUsedCouponsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAllCouponsDelegate;
        
        private EndOperationDelegate onEndAllCouponsDelegate;
        
        private System.Threading.SendOrPostCallback onAllCouponsCompletedDelegate;
        
        private BeginOperationDelegate onBeginTestDelegate;
        
        private EndOperationDelegate onEndTestDelegate;
        
        private System.Threading.SendOrPostCallback onTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SoapServiceSoapClient() {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<HelloWorldCompletedEventArgs> HelloWorldCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<AddAdminCompletedEventArgs> AddAdminCompleted;
        
        public event System.EventHandler<AddClientCompletedEventArgs> AddClientCompleted;
        
        public event System.EventHandler<ValidateCompletedEventArgs> ValidateCompleted;
        
        public event System.EventHandler<UsedCouponsCompletedEventArgs> UsedCouponsCompleted;
        
        public event System.EventHandler<UnUsedCouponsCompletedEventArgs> UnUsedCouponsCompleted;
        
        public event System.EventHandler<AllCouponsCompletedEventArgs> AllCouponsCompleted;
        
        public event System.EventHandler<TestCompletedEventArgs> TestCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginHelloWorld(Appa.ServiceReference1.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginHelloWorld(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.HelloWorldRequest inValue = new Appa.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Appa.ServiceReference1.HelloWorldRequestBody();
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginHelloWorld(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.HelloWorldResponse Appa.ServiceReference1.SoapServiceSoap.EndHelloWorld(System.IAsyncResult result) {
            return base.Channel.EndHelloWorld(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndHelloWorld(System.IAsyncResult result) {
            Appa.ServiceReference1.HelloWorldResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndHelloWorld(result);
            return retVal.Body.HelloWorldResult;
        }
        
        private System.IAsyncResult OnBeginHelloWorld(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginHelloWorld(callback, asyncState);
        }
        
        private object[] OnEndHelloWorld(System.IAsyncResult result) {
            string retVal = this.EndHelloWorld(result);
            return new object[] {
                    retVal};
        }
        
        private void OnHelloWorldCompleted(object state) {
            if ((this.HelloWorldCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        public void HelloWorldAsync(object userState) {
            if ((this.onBeginHelloWorldDelegate == null)) {
                this.onBeginHelloWorldDelegate = new BeginOperationDelegate(this.OnBeginHelloWorld);
            }
            if ((this.onEndHelloWorldDelegate == null)) {
                this.onEndHelloWorldDelegate = new EndOperationDelegate(this.OnEndHelloWorld);
            }
            if ((this.onHelloWorldCompletedDelegate == null)) {
                this.onHelloWorldCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnHelloWorldCompleted);
            }
            base.InvokeAsync(this.onBeginHelloWorldDelegate, null, this.onEndHelloWorldDelegate, this.onHelloWorldCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginLogin(Appa.ServiceReference1.LoginRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginLogin(string shop, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.LoginRequest inValue = new Appa.ServiceReference1.LoginRequest();
            inValue.Body = new Appa.ServiceReference1.LoginRequestBody();
            inValue.Body.shop = shop;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginLogin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.LoginResponse Appa.ServiceReference1.SoapServiceSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndLogin(System.IAsyncResult result) {
            Appa.ServiceReference1.LoginResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndLogin(result);
            return retVal.Body.LoginResult;
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string shop = ((string)(inValues[0]));
            return this.BeginLogin(shop, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            string retVal = this.EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string shop) {
            this.LoginAsync(shop, null);
        }
        
        public void LoginAsync(string shop, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        shop}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginAddAdmin(Appa.ServiceReference1.AddAdminRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddAdmin(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAddAdmin(string shop, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.AddAdminRequest inValue = new Appa.ServiceReference1.AddAdminRequest();
            inValue.Body = new Appa.ServiceReference1.AddAdminRequestBody();
            inValue.Body.shop = shop;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginAddAdmin(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.AddAdminResponse Appa.ServiceReference1.SoapServiceSoap.EndAddAdmin(System.IAsyncResult result) {
            return base.Channel.EndAddAdmin(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndAddAdmin(System.IAsyncResult result) {
            Appa.ServiceReference1.AddAdminResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndAddAdmin(result);
            return retVal.Body.AddAdminResult;
        }
        
        private System.IAsyncResult OnBeginAddAdmin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string shop = ((string)(inValues[0]));
            return this.BeginAddAdmin(shop, callback, asyncState);
        }
        
        private object[] OnEndAddAdmin(System.IAsyncResult result) {
            string retVal = this.EndAddAdmin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddAdminCompleted(object state) {
            if ((this.AddAdminCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddAdminCompleted(this, new AddAdminCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddAdminAsync(string shop) {
            this.AddAdminAsync(shop, null);
        }
        
        public void AddAdminAsync(string shop, object userState) {
            if ((this.onBeginAddAdminDelegate == null)) {
                this.onBeginAddAdminDelegate = new BeginOperationDelegate(this.OnBeginAddAdmin);
            }
            if ((this.onEndAddAdminDelegate == null)) {
                this.onEndAddAdminDelegate = new EndOperationDelegate(this.OnEndAddAdmin);
            }
            if ((this.onAddAdminCompletedDelegate == null)) {
                this.onAddAdminCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddAdminCompleted);
            }
            base.InvokeAsync(this.onBeginAddAdminDelegate, new object[] {
                        shop}, this.onEndAddAdminDelegate, this.onAddAdminCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginAddClient(Appa.ServiceReference1.AddClientRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddClient(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAddClient(string shop, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.AddClientRequest inValue = new Appa.ServiceReference1.AddClientRequest();
            inValue.Body = new Appa.ServiceReference1.AddClientRequestBody();
            inValue.Body.shop = shop;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginAddClient(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.AddClientResponse Appa.ServiceReference1.SoapServiceSoap.EndAddClient(System.IAsyncResult result) {
            return base.Channel.EndAddClient(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndAddClient(System.IAsyncResult result) {
            Appa.ServiceReference1.AddClientResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndAddClient(result);
            return retVal.Body.AddClientResult;
        }
        
        private System.IAsyncResult OnBeginAddClient(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string shop = ((string)(inValues[0]));
            return this.BeginAddClient(shop, callback, asyncState);
        }
        
        private object[] OnEndAddClient(System.IAsyncResult result) {
            string retVal = this.EndAddClient(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddClientCompleted(object state) {
            if ((this.AddClientCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddClientCompleted(this, new AddClientCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddClientAsync(string shop) {
            this.AddClientAsync(shop, null);
        }
        
        public void AddClientAsync(string shop, object userState) {
            if ((this.onBeginAddClientDelegate == null)) {
                this.onBeginAddClientDelegate = new BeginOperationDelegate(this.OnBeginAddClient);
            }
            if ((this.onEndAddClientDelegate == null)) {
                this.onEndAddClientDelegate = new EndOperationDelegate(this.OnEndAddClient);
            }
            if ((this.onAddClientCompletedDelegate == null)) {
                this.onAddClientCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddClientCompleted);
            }
            base.InvokeAsync(this.onBeginAddClientDelegate, new object[] {
                        shop}, this.onEndAddClientDelegate, this.onAddClientCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginValidate(Appa.ServiceReference1.ValidateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginValidate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginValidate(string adminId, string coupon, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.ValidateRequest inValue = new Appa.ServiceReference1.ValidateRequest();
            inValue.Body = new Appa.ServiceReference1.ValidateRequestBody();
            inValue.Body.adminId = adminId;
            inValue.Body.coupon = coupon;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginValidate(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.ValidateResponse Appa.ServiceReference1.SoapServiceSoap.EndValidate(System.IAsyncResult result) {
            return base.Channel.EndValidate(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndValidate(System.IAsyncResult result) {
            Appa.ServiceReference1.ValidateResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndValidate(result);
            return retVal.Body.ValidateResult;
        }
        
        private System.IAsyncResult OnBeginValidate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string adminId = ((string)(inValues[0]));
            string coupon = ((string)(inValues[1]));
            return this.BeginValidate(adminId, coupon, callback, asyncState);
        }
        
        private object[] OnEndValidate(System.IAsyncResult result) {
            string retVal = this.EndValidate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnValidateCompleted(object state) {
            if ((this.ValidateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ValidateCompleted(this, new ValidateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ValidateAsync(string adminId, string coupon) {
            this.ValidateAsync(adminId, coupon, null);
        }
        
        public void ValidateAsync(string adminId, string coupon, object userState) {
            if ((this.onBeginValidateDelegate == null)) {
                this.onBeginValidateDelegate = new BeginOperationDelegate(this.OnBeginValidate);
            }
            if ((this.onEndValidateDelegate == null)) {
                this.onEndValidateDelegate = new EndOperationDelegate(this.OnEndValidate);
            }
            if ((this.onValidateCompletedDelegate == null)) {
                this.onValidateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnValidateCompleted);
            }
            base.InvokeAsync(this.onBeginValidateDelegate, new object[] {
                        adminId,
                        coupon}, this.onEndValidateDelegate, this.onValidateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginUsedCoupons(Appa.ServiceReference1.UsedCouponsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUsedCoupons(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUsedCoupons(string AdminId, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.UsedCouponsRequest inValue = new Appa.ServiceReference1.UsedCouponsRequest();
            inValue.Body = new Appa.ServiceReference1.UsedCouponsRequestBody();
            inValue.Body.AdminId = AdminId;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginUsedCoupons(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.UsedCouponsResponse Appa.ServiceReference1.SoapServiceSoap.EndUsedCoupons(System.IAsyncResult result) {
            return base.Channel.EndUsedCoupons(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndUsedCoupons(System.IAsyncResult result) {
            Appa.ServiceReference1.UsedCouponsResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndUsedCoupons(result);
            return retVal.Body.UsedCouponsResult;
        }
        
        private System.IAsyncResult OnBeginUsedCoupons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string AdminId = ((string)(inValues[0]));
            return this.BeginUsedCoupons(AdminId, callback, asyncState);
        }
        
        private object[] OnEndUsedCoupons(System.IAsyncResult result) {
            string retVal = this.EndUsedCoupons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUsedCouponsCompleted(object state) {
            if ((this.UsedCouponsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UsedCouponsCompleted(this, new UsedCouponsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UsedCouponsAsync(string AdminId) {
            this.UsedCouponsAsync(AdminId, null);
        }
        
        public void UsedCouponsAsync(string AdminId, object userState) {
            if ((this.onBeginUsedCouponsDelegate == null)) {
                this.onBeginUsedCouponsDelegate = new BeginOperationDelegate(this.OnBeginUsedCoupons);
            }
            if ((this.onEndUsedCouponsDelegate == null)) {
                this.onEndUsedCouponsDelegate = new EndOperationDelegate(this.OnEndUsedCoupons);
            }
            if ((this.onUsedCouponsCompletedDelegate == null)) {
                this.onUsedCouponsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUsedCouponsCompleted);
            }
            base.InvokeAsync(this.onBeginUsedCouponsDelegate, new object[] {
                        AdminId}, this.onEndUsedCouponsDelegate, this.onUsedCouponsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginUnUsedCoupons(Appa.ServiceReference1.UnUsedCouponsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUnUsedCoupons(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginUnUsedCoupons(string AdminId, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.UnUsedCouponsRequest inValue = new Appa.ServiceReference1.UnUsedCouponsRequest();
            inValue.Body = new Appa.ServiceReference1.UnUsedCouponsRequestBody();
            inValue.Body.AdminId = AdminId;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginUnUsedCoupons(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.UnUsedCouponsResponse Appa.ServiceReference1.SoapServiceSoap.EndUnUsedCoupons(System.IAsyncResult result) {
            return base.Channel.EndUnUsedCoupons(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndUnUsedCoupons(System.IAsyncResult result) {
            Appa.ServiceReference1.UnUsedCouponsResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndUnUsedCoupons(result);
            return retVal.Body.UnUsedCouponsResult;
        }
        
        private System.IAsyncResult OnBeginUnUsedCoupons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string AdminId = ((string)(inValues[0]));
            return this.BeginUnUsedCoupons(AdminId, callback, asyncState);
        }
        
        private object[] OnEndUnUsedCoupons(System.IAsyncResult result) {
            string retVal = this.EndUnUsedCoupons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUnUsedCouponsCompleted(object state) {
            if ((this.UnUsedCouponsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UnUsedCouponsCompleted(this, new UnUsedCouponsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UnUsedCouponsAsync(string AdminId) {
            this.UnUsedCouponsAsync(AdminId, null);
        }
        
        public void UnUsedCouponsAsync(string AdminId, object userState) {
            if ((this.onBeginUnUsedCouponsDelegate == null)) {
                this.onBeginUnUsedCouponsDelegate = new BeginOperationDelegate(this.OnBeginUnUsedCoupons);
            }
            if ((this.onEndUnUsedCouponsDelegate == null)) {
                this.onEndUnUsedCouponsDelegate = new EndOperationDelegate(this.OnEndUnUsedCoupons);
            }
            if ((this.onUnUsedCouponsCompletedDelegate == null)) {
                this.onUnUsedCouponsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUnUsedCouponsCompleted);
            }
            base.InvokeAsync(this.onBeginUnUsedCouponsDelegate, new object[] {
                        AdminId}, this.onEndUnUsedCouponsDelegate, this.onUnUsedCouponsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginAllCoupons(Appa.ServiceReference1.AllCouponsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAllCoupons(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAllCoupons(string Password, System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.AllCouponsRequest inValue = new Appa.ServiceReference1.AllCouponsRequest();
            inValue.Body = new Appa.ServiceReference1.AllCouponsRequestBody();
            inValue.Body.Password = Password;
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginAllCoupons(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.AllCouponsResponse Appa.ServiceReference1.SoapServiceSoap.EndAllCoupons(System.IAsyncResult result) {
            return base.Channel.EndAllCoupons(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndAllCoupons(System.IAsyncResult result) {
            Appa.ServiceReference1.AllCouponsResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndAllCoupons(result);
            return retVal.Body.AllCouponsResult;
        }
        
        private System.IAsyncResult OnBeginAllCoupons(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Password = ((string)(inValues[0]));
            return this.BeginAllCoupons(Password, callback, asyncState);
        }
        
        private object[] OnEndAllCoupons(System.IAsyncResult result) {
            string retVal = this.EndAllCoupons(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAllCouponsCompleted(object state) {
            if ((this.AllCouponsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AllCouponsCompleted(this, new AllCouponsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AllCouponsAsync(string Password) {
            this.AllCouponsAsync(Password, null);
        }
        
        public void AllCouponsAsync(string Password, object userState) {
            if ((this.onBeginAllCouponsDelegate == null)) {
                this.onBeginAllCouponsDelegate = new BeginOperationDelegate(this.OnBeginAllCoupons);
            }
            if ((this.onEndAllCouponsDelegate == null)) {
                this.onEndAllCouponsDelegate = new EndOperationDelegate(this.OnEndAllCoupons);
            }
            if ((this.onAllCouponsCompletedDelegate == null)) {
                this.onAllCouponsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAllCouponsCompleted);
            }
            base.InvokeAsync(this.onBeginAllCouponsDelegate, new object[] {
                        Password}, this.onEndAllCouponsDelegate, this.onAllCouponsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Appa.ServiceReference1.SoapServiceSoap.BeginTest(Appa.ServiceReference1.TestRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginTest(System.AsyncCallback callback, object asyncState) {
            Appa.ServiceReference1.TestRequest inValue = new Appa.ServiceReference1.TestRequest();
            inValue.Body = new Appa.ServiceReference1.TestRequestBody();
            return ((Appa.ServiceReference1.SoapServiceSoap)(this)).BeginTest(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Appa.ServiceReference1.TestResponse Appa.ServiceReference1.SoapServiceSoap.EndTest(System.IAsyncResult result) {
            return base.Channel.EndTest(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndTest(System.IAsyncResult result) {
            Appa.ServiceReference1.TestResponse retVal = ((Appa.ServiceReference1.SoapServiceSoap)(this)).EndTest(result);
            return retVal.Body.TestResult;
        }
        
        private System.IAsyncResult OnBeginTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginTest(callback, asyncState);
        }
        
        private object[] OnEndTest(System.IAsyncResult result) {
            string retVal = this.EndTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestCompleted(object state) {
            if ((this.TestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestCompleted(this, new TestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        public void TestAsync(object userState) {
            if ((this.onBeginTestDelegate == null)) {
                this.onBeginTestDelegate = new BeginOperationDelegate(this.OnBeginTest);
            }
            if ((this.onEndTestDelegate == null)) {
                this.onEndTestDelegate = new EndOperationDelegate(this.OnEndTest);
            }
            if ((this.onTestCompletedDelegate == null)) {
                this.onTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestCompleted);
            }
            base.InvokeAsync(this.onBeginTestDelegate, null, this.onEndTestDelegate, this.onTestCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Appa.ServiceReference1.SoapServiceSoap CreateChannel() {
            return new SoapServiceSoapClientChannel(this);
        }
        
        private class SoapServiceSoapClientChannel : ChannelBase<Appa.ServiceReference1.SoapServiceSoap>, Appa.ServiceReference1.SoapServiceSoap {
            
            public SoapServiceSoapClientChannel(System.ServiceModel.ClientBase<Appa.ServiceReference1.SoapServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginHelloWorld(Appa.ServiceReference1.HelloWorldRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("HelloWorld", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.HelloWorldResponse EndHelloWorld(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.HelloWorldResponse _result = ((Appa.ServiceReference1.HelloWorldResponse)(base.EndInvoke("HelloWorld", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogin(Appa.ServiceReference1.LoginRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.LoginResponse EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.LoginResponse _result = ((Appa.ServiceReference1.LoginResponse)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddAdmin(Appa.ServiceReference1.AddAdminRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddAdmin", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.AddAdminResponse EndAddAdmin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.AddAdminResponse _result = ((Appa.ServiceReference1.AddAdminResponse)(base.EndInvoke("AddAdmin", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAddClient(Appa.ServiceReference1.AddClientRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AddClient", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.AddClientResponse EndAddClient(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.AddClientResponse _result = ((Appa.ServiceReference1.AddClientResponse)(base.EndInvoke("AddClient", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginValidate(Appa.ServiceReference1.ValidateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Validate", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.ValidateResponse EndValidate(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.ValidateResponse _result = ((Appa.ServiceReference1.ValidateResponse)(base.EndInvoke("Validate", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUsedCoupons(Appa.ServiceReference1.UsedCouponsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UsedCoupons", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.UsedCouponsResponse EndUsedCoupons(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.UsedCouponsResponse _result = ((Appa.ServiceReference1.UsedCouponsResponse)(base.EndInvoke("UsedCoupons", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUnUsedCoupons(Appa.ServiceReference1.UnUsedCouponsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("UnUsedCoupons", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.UnUsedCouponsResponse EndUnUsedCoupons(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.UnUsedCouponsResponse _result = ((Appa.ServiceReference1.UnUsedCouponsResponse)(base.EndInvoke("UnUsedCoupons", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAllCoupons(Appa.ServiceReference1.AllCouponsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AllCoupons", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.AllCouponsResponse EndAllCoupons(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.AllCouponsResponse _result = ((Appa.ServiceReference1.AllCouponsResponse)(base.EndInvoke("AllCoupons", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginTest(Appa.ServiceReference1.TestRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Test", _args, callback, asyncState);
                return _result;
            }
            
            public Appa.ServiceReference1.TestResponse EndTest(System.IAsyncResult result) {
                object[] _args = new object[0];
                Appa.ServiceReference1.TestResponse _result = ((Appa.ServiceReference1.TestResponse)(base.EndInvoke("Test", _args, result)));
                return _result;
            }
        }
    }
}
