//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoDB.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.RecipeServiceSoap")]
    public interface RecipeServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MongoDB.ServiceReference1.HelloWorldResponse HelloWorld(MongoDB.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.HelloWorldResponse> HelloWorldAsync(MongoDB.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name js from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        MongoDB.ServiceReference1.AddResponse Add(MongoDB.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.AddResponse> AddAsync(MongoDB.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync();
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        MongoDB.ServiceReference1.SearchResponse Search(MongoDB.ServiceReference1.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.SearchResponse> SearchAsync(MongoDB.ServiceReference1.SearchRequest request);
        
        // CODEGEN: Generating message contract since element name ItemPerTimeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemPerTime", ReplyAction="*")]
        MongoDB.ServiceReference1.ItemPerTimeResponse ItemPerTime(MongoDB.ServiceReference1.ItemPerTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItemPerTime", ReplyAction="*")]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.ItemPerTimeResponse> ItemPerTimeAsync(MongoDB.ServiceReference1.ItemPerTimeRequest request);
        
        // CODEGEN: Generating message contract since element name DataAnalyticsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataAnalytics", ReplyAction="*")]
        MongoDB.ServiceReference1.DataAnalyticsResponse DataAnalytics(MongoDB.ServiceReference1.DataAnalyticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataAnalytics", ReplyAction="*")]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.DataAnalyticsResponse> DataAnalyticsAsync(MongoDB.ServiceReference1.DataAnalyticsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MongoDB.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MongoDB.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(MongoDB.ServiceReference1.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string js;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string js) {
            this.js = js;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(MongoDB.ServiceReference1.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(string AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.SearchRequestBody Body;
        
        public SearchRequest() {
        }
        
        public SearchRequest(MongoDB.ServiceReference1.SearchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        public SearchRequestBody() {
        }
        
        public SearchRequestBody(string key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.SearchResponseBody Body;
        
        public SearchResponse() {
        }
        
        public SearchResponse(MongoDB.ServiceReference1.SearchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchResult;
        
        public SearchResponseBody() {
        }
        
        public SearchResponseBody(string SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ItemPerTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ItemPerTime", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.ItemPerTimeRequestBody Body;
        
        public ItemPerTimeRequest() {
        }
        
        public ItemPerTimeRequest(MongoDB.ServiceReference1.ItemPerTimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ItemPerTimeRequestBody {
        
        public ItemPerTimeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ItemPerTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ItemPerTimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.ItemPerTimeResponseBody Body;
        
        public ItemPerTimeResponse() {
        }
        
        public ItemPerTimeResponse(MongoDB.ServiceReference1.ItemPerTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemPerTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ItemPerTimeResult;
        
        public ItemPerTimeResponseBody() {
        }
        
        public ItemPerTimeResponseBody(string ItemPerTimeResult) {
            this.ItemPerTimeResult = ItemPerTimeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataAnalyticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataAnalytics", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.DataAnalyticsRequestBody Body;
        
        public DataAnalyticsRequest() {
        }
        
        public DataAnalyticsRequest(MongoDB.ServiceReference1.DataAnalyticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DataAnalyticsRequestBody {
        
        public DataAnalyticsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DataAnalyticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DataAnalyticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MongoDB.ServiceReference1.DataAnalyticsResponseBody Body;
        
        public DataAnalyticsResponse() {
        }
        
        public DataAnalyticsResponse(MongoDB.ServiceReference1.DataAnalyticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DataAnalyticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DataAnalyticsResult;
        
        public DataAnalyticsResponseBody() {
        }
        
        public DataAnalyticsResponseBody(string DataAnalyticsResult) {
            this.DataAnalyticsResult = DataAnalyticsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecipeServiceSoapChannel : MongoDB.ServiceReference1.RecipeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipeServiceSoapClient : System.ServiceModel.ClientBase<MongoDB.ServiceReference1.RecipeServiceSoap>, MongoDB.ServiceReference1.RecipeServiceSoap {
        
        public RecipeServiceSoapClient() {
        }
        
        public RecipeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MongoDB.ServiceReference1.HelloWorldResponse MongoDB.ServiceReference1.RecipeServiceSoap.HelloWorld(MongoDB.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MongoDB.ServiceReference1.HelloWorldRequest inValue = new MongoDB.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MongoDB.ServiceReference1.HelloWorldRequestBody();
            MongoDB.ServiceReference1.HelloWorldResponse retVal = ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.HelloWorldResponse> MongoDB.ServiceReference1.RecipeServiceSoap.HelloWorldAsync(MongoDB.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MongoDB.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            MongoDB.ServiceReference1.HelloWorldRequest inValue = new MongoDB.ServiceReference1.HelloWorldRequest();
            inValue.Body = new MongoDB.ServiceReference1.HelloWorldRequestBody();
            return ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MongoDB.ServiceReference1.AddResponse MongoDB.ServiceReference1.RecipeServiceSoap.Add(MongoDB.ServiceReference1.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public string Add(string js) {
            MongoDB.ServiceReference1.AddRequest inValue = new MongoDB.ServiceReference1.AddRequest();
            inValue.Body = new MongoDB.ServiceReference1.AddRequestBody();
            inValue.Body.js = js;
            MongoDB.ServiceReference1.AddResponse retVal = ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.AddResponse> MongoDB.ServiceReference1.RecipeServiceSoap.AddAsync(MongoDB.ServiceReference1.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<MongoDB.ServiceReference1.AddResponse> AddAsync(string js) {
            MongoDB.ServiceReference1.AddRequest inValue = new MongoDB.ServiceReference1.AddRequest();
            inValue.Body = new MongoDB.ServiceReference1.AddRequestBody();
            inValue.Body.js = js;
            return ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).AddAsync(inValue);
        }
        
        public void Delete() {
            base.Channel.Delete();
        }
        
        public System.Threading.Tasks.Task DeleteAsync() {
            return base.Channel.DeleteAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MongoDB.ServiceReference1.SearchResponse MongoDB.ServiceReference1.RecipeServiceSoap.Search(MongoDB.ServiceReference1.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public string Search(string key) {
            MongoDB.ServiceReference1.SearchRequest inValue = new MongoDB.ServiceReference1.SearchRequest();
            inValue.Body = new MongoDB.ServiceReference1.SearchRequestBody();
            inValue.Body.key = key;
            MongoDB.ServiceReference1.SearchResponse retVal = ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).Search(inValue);
            return retVal.Body.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.SearchResponse> MongoDB.ServiceReference1.RecipeServiceSoap.SearchAsync(MongoDB.ServiceReference1.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<MongoDB.ServiceReference1.SearchResponse> SearchAsync(string key) {
            MongoDB.ServiceReference1.SearchRequest inValue = new MongoDB.ServiceReference1.SearchRequest();
            inValue.Body = new MongoDB.ServiceReference1.SearchRequestBody();
            inValue.Body.key = key;
            return ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).SearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MongoDB.ServiceReference1.ItemPerTimeResponse MongoDB.ServiceReference1.RecipeServiceSoap.ItemPerTime(MongoDB.ServiceReference1.ItemPerTimeRequest request) {
            return base.Channel.ItemPerTime(request);
        }
        
        public string ItemPerTime() {
            MongoDB.ServiceReference1.ItemPerTimeRequest inValue = new MongoDB.ServiceReference1.ItemPerTimeRequest();
            inValue.Body = new MongoDB.ServiceReference1.ItemPerTimeRequestBody();
            MongoDB.ServiceReference1.ItemPerTimeResponse retVal = ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).ItemPerTime(inValue);
            return retVal.Body.ItemPerTimeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.ItemPerTimeResponse> MongoDB.ServiceReference1.RecipeServiceSoap.ItemPerTimeAsync(MongoDB.ServiceReference1.ItemPerTimeRequest request) {
            return base.Channel.ItemPerTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<MongoDB.ServiceReference1.ItemPerTimeResponse> ItemPerTimeAsync() {
            MongoDB.ServiceReference1.ItemPerTimeRequest inValue = new MongoDB.ServiceReference1.ItemPerTimeRequest();
            inValue.Body = new MongoDB.ServiceReference1.ItemPerTimeRequestBody();
            return ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).ItemPerTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MongoDB.ServiceReference1.DataAnalyticsResponse MongoDB.ServiceReference1.RecipeServiceSoap.DataAnalytics(MongoDB.ServiceReference1.DataAnalyticsRequest request) {
            return base.Channel.DataAnalytics(request);
        }
        
        public string DataAnalytics() {
            MongoDB.ServiceReference1.DataAnalyticsRequest inValue = new MongoDB.ServiceReference1.DataAnalyticsRequest();
            inValue.Body = new MongoDB.ServiceReference1.DataAnalyticsRequestBody();
            MongoDB.ServiceReference1.DataAnalyticsResponse retVal = ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).DataAnalytics(inValue);
            return retVal.Body.DataAnalyticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MongoDB.ServiceReference1.DataAnalyticsResponse> MongoDB.ServiceReference1.RecipeServiceSoap.DataAnalyticsAsync(MongoDB.ServiceReference1.DataAnalyticsRequest request) {
            return base.Channel.DataAnalyticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MongoDB.ServiceReference1.DataAnalyticsResponse> DataAnalyticsAsync() {
            MongoDB.ServiceReference1.DataAnalyticsRequest inValue = new MongoDB.ServiceReference1.DataAnalyticsRequest();
            inValue.Body = new MongoDB.ServiceReference1.DataAnalyticsRequestBody();
            return ((MongoDB.ServiceReference1.RecipeServiceSoap)(this)).DataAnalyticsAsync(inValue);
        }
    }
}
