//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopAdmins", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ShopAdmins : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopLists", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ShopLists : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        private int OfferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CouponCodeField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Offer {
            get {
                return this.OfferField;
            }
            set {
                if ((this.OfferField.Equals(value) != true)) {
                    this.OfferField = value;
                    this.RaisePropertyChanged("Offer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExpiryDateTime {
            get {
                return this.ExpiryDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateTimeField, value) != true)) {
                    this.ExpiryDateTimeField = value;
                    this.RaisePropertyChanged("ExpiryDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CouponCode {
            get {
                return this.CouponCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CouponCodeField, value) != true)) {
                    this.CouponCodeField = value;
                    this.RaisePropertyChanged("CouponCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AdminId {
            get {
                return this.AdminIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminIdField, value) != true)) {
                    this.AdminIdField = value;
                    this.RaisePropertyChanged("AdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ValidatedDateTime {
            get {
                return this.ValidatedDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidatedDateTimeField, value) != true)) {
                    this.ValidatedDateTimeField = value;
                    this.RaisePropertyChanged("ValidatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDateTimeField, value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SoapServiceSoap")]
    public interface SoapServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        CouponService.ServiceReference1.HelloWorldResponse HelloWorld(CouponService.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name shopAdmins from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        CouponService.ServiceReference1.LoginResponse Login(CouponService.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name shopAdmins from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAdmin", ReplyAction="*")]
        CouponService.ServiceReference1.AddAdminResponse AddAdmin(CouponService.ServiceReference1.AddAdminRequest request);
        
        // CODEGEN: Generating message contract since element name shopLists from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddClient", ReplyAction="*")]
        CouponService.ServiceReference1.AddClientResponse AddClient(CouponService.ServiceReference1.AddClientRequest request);
        
        // CODEGEN: Generating message contract since element name adminId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate", ReplyAction="*")]
        CouponService.ServiceReference1.ValidateResponse Validate(CouponService.ServiceReference1.ValidateRequest request);
        
        // CODEGEN: Generating message contract since element name AdminId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsedCoupons", ReplyAction="*")]
        CouponService.ServiceReference1.UsedCouponsResponse UsedCoupons(CouponService.ServiceReference1.UsedCouponsRequest request);
        
        // CODEGEN: Generating message contract since element name AdminId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UnUsedCoupons", ReplyAction="*")]
        CouponService.ServiceReference1.UnUsedCouponsResponse UnUsedCoupons(CouponService.ServiceReference1.UnUsedCouponsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(CouponService.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(CouponService.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(CouponService.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CouponService.ServiceReference1.ShopAdmins shopAdmins;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(CouponService.ServiceReference1.ShopAdmins shopAdmins) {
            this.shopAdmins = shopAdmins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(CouponService.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAdmin", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.AddAdminRequestBody Body;
        
        public AddAdminRequest() {
        }
        
        public AddAdminRequest(CouponService.ServiceReference1.AddAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CouponService.ServiceReference1.ShopAdmins shopAdmins;
        
        public AddAdminRequestBody() {
        }
        
        public AddAdminRequestBody(CouponService.ServiceReference1.ShopAdmins shopAdmins) {
            this.shopAdmins = shopAdmins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.AddAdminResponseBody Body;
        
        public AddAdminResponse() {
        }
        
        public AddAdminResponse(CouponService.ServiceReference1.AddAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddAdminResult;
        
        public AddAdminResponseBody() {
        }
        
        public AddAdminResponseBody(string AddAdminResult) {
            this.AddAdminResult = AddAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClient", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.AddClientRequestBody Body;
        
        public AddClientRequest() {
        }
        
        public AddClientRequest(CouponService.ServiceReference1.AddClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CouponService.ServiceReference1.ShopLists shopLists;
        
        public AddClientRequestBody() {
        }
        
        public AddClientRequestBody(CouponService.ServiceReference1.ShopLists shopLists) {
            this.shopLists = shopLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.AddClientResponseBody Body;
        
        public AddClientResponse() {
        }
        
        public AddClientResponse(CouponService.ServiceReference1.AddClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddClientResult;
        
        public AddClientResponseBody() {
        }
        
        public AddClientResponseBody(string AddClientResult) {
            this.AddClientResult = AddClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(CouponService.ServiceReference1.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string adminId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string coupon;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string adminId, string coupon) {
            this.adminId = adminId;
            this.coupon = coupon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(CouponService.ServiceReference1.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(string ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsedCouponsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsedCoupons", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.UsedCouponsRequestBody Body;
        
        public UsedCouponsRequest() {
        }
        
        public UsedCouponsRequest(CouponService.ServiceReference1.UsedCouponsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsedCouponsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdminId;
        
        public UsedCouponsRequestBody() {
        }
        
        public UsedCouponsRequestBody(string AdminId) {
            this.AdminId = AdminId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsedCouponsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsedCouponsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.UsedCouponsResponseBody Body;
        
        public UsedCouponsResponse() {
        }
        
        public UsedCouponsResponse(CouponService.ServiceReference1.UsedCouponsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UsedCouponsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CouponService.ServiceReference1.ShopLists[] UsedCouponsResult;
        
        public UsedCouponsResponseBody() {
        }
        
        public UsedCouponsResponseBody(CouponService.ServiceReference1.ShopLists[] UsedCouponsResult) {
            this.UsedCouponsResult = UsedCouponsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnUsedCouponsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnUsedCoupons", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.UnUsedCouponsRequestBody Body;
        
        public UnUsedCouponsRequest() {
        }
        
        public UnUsedCouponsRequest(CouponService.ServiceReference1.UnUsedCouponsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnUsedCouponsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdminId;
        
        public UnUsedCouponsRequestBody() {
        }
        
        public UnUsedCouponsRequestBody(string AdminId) {
            this.AdminId = AdminId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UnUsedCouponsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UnUsedCouponsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CouponService.ServiceReference1.UnUsedCouponsResponseBody Body;
        
        public UnUsedCouponsResponse() {
        }
        
        public UnUsedCouponsResponse(CouponService.ServiceReference1.UnUsedCouponsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UnUsedCouponsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CouponService.ServiceReference1.ShopLists[] UnUsedCouponsResult;
        
        public UnUsedCouponsResponseBody() {
        }
        
        public UnUsedCouponsResponseBody(CouponService.ServiceReference1.ShopLists[] UnUsedCouponsResult) {
            this.UnUsedCouponsResult = UnUsedCouponsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapServiceSoapChannel : CouponService.ServiceReference1.SoapServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceSoapClient : System.ServiceModel.ClientBase<CouponService.ServiceReference1.SoapServiceSoap>, CouponService.ServiceReference1.SoapServiceSoap {
        
        public SoapServiceSoapClient() {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.HelloWorldResponse CouponService.ServiceReference1.SoapServiceSoap.HelloWorld(CouponService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            CouponService.ServiceReference1.HelloWorldRequest inValue = new CouponService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new CouponService.ServiceReference1.HelloWorldRequestBody();
            CouponService.ServiceReference1.HelloWorldResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.LoginResponse CouponService.ServiceReference1.SoapServiceSoap.Login(CouponService.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(CouponService.ServiceReference1.ShopAdmins shopAdmins) {
            CouponService.ServiceReference1.LoginRequest inValue = new CouponService.ServiceReference1.LoginRequest();
            inValue.Body = new CouponService.ServiceReference1.LoginRequestBody();
            inValue.Body.shopAdmins = shopAdmins;
            CouponService.ServiceReference1.LoginResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.AddAdminResponse CouponService.ServiceReference1.SoapServiceSoap.AddAdmin(CouponService.ServiceReference1.AddAdminRequest request) {
            return base.Channel.AddAdmin(request);
        }
        
        public string AddAdmin(CouponService.ServiceReference1.ShopAdmins shopAdmins) {
            CouponService.ServiceReference1.AddAdminRequest inValue = new CouponService.ServiceReference1.AddAdminRequest();
            inValue.Body = new CouponService.ServiceReference1.AddAdminRequestBody();
            inValue.Body.shopAdmins = shopAdmins;
            CouponService.ServiceReference1.AddAdminResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).AddAdmin(inValue);
            return retVal.Body.AddAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.AddClientResponse CouponService.ServiceReference1.SoapServiceSoap.AddClient(CouponService.ServiceReference1.AddClientRequest request) {
            return base.Channel.AddClient(request);
        }
        
        public string AddClient(CouponService.ServiceReference1.ShopLists shopLists) {
            CouponService.ServiceReference1.AddClientRequest inValue = new CouponService.ServiceReference1.AddClientRequest();
            inValue.Body = new CouponService.ServiceReference1.AddClientRequestBody();
            inValue.Body.shopLists = shopLists;
            CouponService.ServiceReference1.AddClientResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).AddClient(inValue);
            return retVal.Body.AddClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.ValidateResponse CouponService.ServiceReference1.SoapServiceSoap.Validate(CouponService.ServiceReference1.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public string Validate(string adminId, string coupon) {
            CouponService.ServiceReference1.ValidateRequest inValue = new CouponService.ServiceReference1.ValidateRequest();
            inValue.Body = new CouponService.ServiceReference1.ValidateRequestBody();
            inValue.Body.adminId = adminId;
            inValue.Body.coupon = coupon;
            CouponService.ServiceReference1.ValidateResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.UsedCouponsResponse CouponService.ServiceReference1.SoapServiceSoap.UsedCoupons(CouponService.ServiceReference1.UsedCouponsRequest request) {
            return base.Channel.UsedCoupons(request);
        }
        
        public CouponService.ServiceReference1.ShopLists[] UsedCoupons(string AdminId) {
            CouponService.ServiceReference1.UsedCouponsRequest inValue = new CouponService.ServiceReference1.UsedCouponsRequest();
            inValue.Body = new CouponService.ServiceReference1.UsedCouponsRequestBody();
            inValue.Body.AdminId = AdminId;
            CouponService.ServiceReference1.UsedCouponsResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).UsedCoupons(inValue);
            return retVal.Body.UsedCouponsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CouponService.ServiceReference1.UnUsedCouponsResponse CouponService.ServiceReference1.SoapServiceSoap.UnUsedCoupons(CouponService.ServiceReference1.UnUsedCouponsRequest request) {
            return base.Channel.UnUsedCoupons(request);
        }
        
        public CouponService.ServiceReference1.ShopLists[] UnUsedCoupons(string AdminId) {
            CouponService.ServiceReference1.UnUsedCouponsRequest inValue = new CouponService.ServiceReference1.UnUsedCouponsRequest();
            inValue.Body = new CouponService.ServiceReference1.UnUsedCouponsRequestBody();
            inValue.Body.AdminId = AdminId;
            CouponService.ServiceReference1.UnUsedCouponsResponse retVal = ((CouponService.ServiceReference1.SoapServiceSoap)(this)).UnUsedCoupons(inValue);
            return retVal.Body.UnUsedCouponsResult;
        }
    }
}
